### ISSUE TITLE
on release

### ISSUE THREAD

**Issue by sudhanshugairola** [AnavrinApps/flutter_plugins#1]
after completing offer, reward status shows nothing and second thing is their is no option to store reward amount into firestore database.

``import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:hiddentechgaming/components/rounded_button.dart';
import 'package:flutter_svg/svg.dart';
import 'dart:async';
import 'package:flutter_tapjoy/flutter_tapjoy.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../constants.dart';

void main() async {
runApp(TapJoy());
}

class TapJoy extends StatefulWidget {
@override
_MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
int ccoins = 0;
int total = 0;
final firestoreInstance = Firestore.instance;
final databaseReference = Firestore.instance;

Future initTapjoy() async {
Tapjoy.instance.setDebugEnabled(isDebug: false);
Tapjoy.instance.setUserConsent(consent: 'consent');
Tapjoy.instance.connect(
apiToken:
'frkd7Rf2RXWtW_DAnxgp4wECHdJes13cZBYzpA1V4MeHpVAdeWHyBSWPNzbA');
Tapjoy.instance.setOnTapjoyConnectSuccessListener(tapjoySuccess);
Tapjoy.instance.setonPlacementRequestFailureListener(tapjoyError);
Tapjoy.instance.setonRewardRequestListener(tapjoyReward);
Tapjoy.instance.setonContentReadyListener(tapjoyisReady);
}

void tapjoySuccess() {
Tapjoy.instance.getPlacement(placementName: 'Appearn');
print('tapjoy success');
}

void tapjoyError(String error) {
print('Tapjoy Placement ERROR: $error');
}

void tapjoyReward(int quantity) async {
print('Tapjoy SDK $quantity');
SharedPreferences prefs = await SharedPreferences.getInstance();
setState(() {
total = (ccoins += quantity) * (prefs.getInt('counter') ?? 0);
prefs.setInt('counter', ccoins);
});
var firebaseUser = await FirebaseAuth.instance.currentUser();
firestoreInstance.collection("coins").document(firebaseUser.uid).setData({
"coins": ccoins,
}).then((_) {
print("success!");
});
}

void tapjoyisReady() {
Tapjoy.instance.showContent();
print('Tapjoy SDK Ready');
}

@override
void initState() {
initTapjoy();
_subt();
_loadCounter();
super.initState();
}

_loadCounter() async {
SharedPreferences prefs = await SharedPreferences.getInstance();
setState(() {
ccoins = _subt() + (prefs.getInt('counter'));
});
}

_subt() async {
var firebaseUser = await FirebaseAuth.instance.currentUser();
firestoreInstance
.collection("coins")
.document(firebaseUser.uid)
.get()
.then((value) {
print(value.data);
setState(() => ccoins = value.data['coins'].toInt());
});
}

@override
Widget build(BuildContext context) {
return MaterialApp(
home: Scaffold(
appBar: buildAppBar(),
body: Center(
child: Column(
children: [
RoundedButton(
text: "Content Available ?",
press: () async {
Tapjoy.instance.requestContent();
},
),
],
),
),
),
debugShowCheckedModeBanner: false);
}

AppBar buildAppBar() {
return AppBar(
title: Text("Tapjoy"),
backgroundColor: Colors.deepPurple,
elevation: 0,
leading: IconButton(
icon: SvgPicture.asset(
"",
),
onPressed: () {},
),
actions: [
IconButton(
icon: Text("Coin$ccoins"),
onPressed: () async {},
),
SizedBox(width: kDefaultPaddin / 1)
],
);
}
}`

**Comment by Sudhanshu-Gairola** [comment]
on watching ads or complete offerwall reward status section remain null not show on going offer

**Comment by arnavvaryani** [comment]
1. You receive callback in form of int from the method you specify in the Tapjoy Reward Listener. 
2. Please check if you are using the latest version of flutter_tapjoy
3. To store your rewards integrate firebase refer, https://github.com/FirebaseExtended/flutterfire
