### ISSUE TITLE
tapjoy  --- ios

### ISSUE THREAD

**Issue by hellosuperX** [AnavrinApps/flutter_plugins#2]
MissingPluginException(No implementation found for method requestContent on channel native)

**Comment by arnavvaryani** [comment]
Hi @hellosuperX can you try updating the dependency and check if you still face the same issue?

**Comment by artemki2077** [comment]
Hello, I got the same error when running the code from the example only with my api_key and TJPlacement, I updated all the dependencies, and no matter how I ran it, I still got this error
