### ISSUE TITLE
Banner ads never load successfully, Mopub Flutter

### ISSUE THREAD

**Issue by Hassico** [AnavrinApps/flutter_plugins#3]
It keeps saying ad failed to load. Reward ads work perfectly though and I waited several days and tried loading banner ads for almost a week and they never worked. It seems that every bammer ad is a tapjoy call id I am not mistaken. Also, can you update the documentation in a way to know how to use mediation and adding adapters please, cuz there is nothing on the ineternet on how to use adapters in flutter. Thank you very much.

**Comment by arnavvaryani** [comment]
Tapjoy doesn't support banner ads. As for the Mopub banners please check if you had a good fill rate and have integrated the plugin with your respective app id's listed on your console.
