### ISSUE TITLE
How to use mediation in mopub package?

### ISSUE THREAD

**Issue by Hassico** [AnavrinApps/flutter_plugins#5]
Please tell me how to get my app ready to use mediation using your mopub plugin. Please reply.
Thank you.

**Comment by anass-naoushi** [comment]
Also, what are the supported mediation networks.

**Comment by Hassico** [comment]
@arnavvaryani , can you please answer these questions

**Comment by arnavvaryani** [comment]
Hi!
To see which networks are supported in Mopub & integration guide, refer https://developers.mopub.com/publishers/mediation/integrate/

I am not the official author for Mopub Flutter, this is a fork published on pub.dev, you can see the original repo here - 
https://github.com/bohdanuhryn/mopub_flutter

And you can also see this file 
https://github.com/bohdanuhryn/mopub_flutter/blob/master/android/build.gradle
where there is admob mediation added internally in the plugin. So if you would like to add more networks you will have to fork his repo add your networks and integrate it in your pubspec.yaml file.

If you still face issues, feel free to open this issue.
